-- CreateTables.sql
-- Poteto.WebAPI用テーブル定義
-- Oracle19c向けのSQLスクリプト

-- 1. Users テーブルの作成
CREATE TABLE Users (
    UserId         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserName       VARCHAR2(50) NOT NULL UNIQUE,
    Email          VARCHAR2(100) NOT NULL UNIQUE,
    PasswordHash   VARCHAR2(256) NOT NULL,
    CreatedAt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt      TIMESTAMP
);

-- 2. Tweets テーブルの作成
CREATE TABLE Tweets (
    TweetId    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId     NUMBER NOT NULL,
    Content    VARCHAR2(280) NOT NULL,
    CreatedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt  TIMESTAMP,
    CONSTRAINT FK_Tweets_Users FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

-- 3. Comments テーブルの作成
CREATE TABLE Comments (
    CommentId  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TweetId    NUMBER NOT NULL,
    UserId     NUMBER NOT NULL,
    Content    VARCHAR2(500) NOT NULL,
    CreatedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Comments_Tweets FOREIGN KEY (TweetId) REFERENCES Tweets(TweetId),
    CONSTRAINT FK_Comments_Users FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

-- 4. Follows テーブルの作成
CREATE TABLE Follows (
    FollowId   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FollowerId NUMBER NOT NULL,
    FolloweeId NUMBER NOT NULL,
    CreatedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Follows_Follower FOREIGN KEY (FollowerId) REFERENCES Users(UserId),
    CONSTRAINT FK_Follows_Followee FOREIGN KEY (FolloweeId) REFERENCES Users(UserId),
    CONSTRAINT UQ_Follows UNIQUE (FollowerId, FolloweeId)
);

-- 5. Blocks テーブルの作成
CREATE TABLE Blocks (
    BlockId    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BlockerId  NUMBER NOT NULL,
    BlockedId  NUMBER NOT NULL,
    CreatedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Blocks_Blocker FOREIGN KEY (BlockerId) REFERENCES Users(UserId),
    CONSTRAINT FK_Blocks_Blocked FOREIGN KEY (BlockedId) REFERENCES Users(UserId),
    CONSTRAINT UQ_Blocks UNIQUE (BlockerId, BlockedId)
);

-- 6. Likes テーブルの作成
CREATE TABLE Likes (
    LikeId    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TweetId   NUMBER NOT NULL,
    UserId    NUMBER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Likes_Tweets FOREIGN KEY (TweetId) REFERENCES Tweets(TweetId),
    CONSTRAINT FK_Likes_Users FOREIGN KEY (UserId) REFERENCES Users(UserId),
    CONSTRAINT UQ_Likes UNIQUE (TweetId, UserId)
);
